# .graphclientrc.yml
sources:
  - name: cdp
    handler:
      graphql:
        endpoint: http://localhost:8765/subgraphs/name/yusupovai/cdp
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 100

documents:
  - ./scripts/query.graphql
