# .graphclientrc.yml
sources:
  - name: cdp
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/zkbob/cdp-nft-polygon
    transforms:
      - autoPagination:
          validateSchema: true
          limitOfRecords: 100

documents:
  - ./scripts/query.graphql
