version: '3'
services:
  bot:
    build: .
    image: ghcr.io/zkbob/cdp-nft-liqbot:main
    env_file: ./scripts/.env
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: ${SYSLOG_DESTINATION}
        tag: "{{.Name}}/{{.ID}}"
