[profile.default]
src = 'contracts/src'
out = 'contracts/out'
test = 'contracts/test'
libs = ['contracts/lib']
remappings = ["@solmate/=contracts/lib/solmate/", "@cdp/=contracts/lib/stable-nft/", "@univ3-core/=contracts/lib/stable-nft/lib/@uniswap/v3-core/contracts/", "@univ3-periphery/=contracts/lib/stable-nft/lib/@uniswap/v3-periphery/contracts/", "@cdp-lib/=contracts/lib/stable-nft/src/libraries/external/", "@zkbob/=contracts/lib/stable-nft/lib/@zkbob/src/"]
optimizer = true

[profile.default.optimizer_details]
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
