name: test

on: ["push", "pull_request"]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install yarn dependencies
        run: yarn

      - name: Check prettier contracts
        run: yarn prettier:check-solidity
      
      - name: Check prettier scripts
        run: yarn prettier:check-scripts

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
